# Generated by Django 5.0.6 on 2024-06-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='cuit',
            field=models.CharField(max_length=13),
        ),
    ]
