# Generated by Django 5.0.6 on 2024-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_upload_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='cuit',
            field=models.CharField(max_length=11),
        ),
    ]
